import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-oil-gas-joint-interest-billing-audit",
  "engine": "recovery",
  "title": "Oil & Gas Joint Interest Billing Audit",
  "shortTitle": "JIB Audit Recovery",
  "tagline": "Audit operator billings, enforce COPAS terms, and recover unsupported working-interest costs",
  "industry": "Oil & Gas Joint Venture Accounting",
  "uiPort": 4555,
  "apiPort": 5555,
  "accent": "#92400e",
  "currency": "USD",
  "primaryOutcome": "Unsupported joint-interest billings recovered with well, AFE, ownership, and COPAS evidence",
  "valueNarrative": "Reconcile JIB statements to division of interest, AFEs, field activity, overhead rules, material transfers, and audit deadlines.",
  "calculation": {
    "actualKey": "billedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Operator billed amount",
    "expectedLabel": "Supported working-interest share",
    "varianceLabel": "Potential JIB recovery",
    "direction": "actual-minus-expected",
    "finding": "Ownership, AFE, field-cost, and accounting-procedure evidence indicate unsupported joint-interest billing.",
    "actions": [
      "Validate division of interest and effective ownership",
      "Reconcile charges to AFE authority and field evidence",
      "Apply COPAS overhead, material, and audit rules",
      "Submit exception and reconcile operator credit"
    ]
  }
},[
feature("operator-and-property-registry","JAR01","Operator and property registry","Reconcile operator and property registry using JOAs, COPAS accounting procedures, division-of-interest records, AFEs, field tickets, material transfers, and JIB statements.","Produce a governed operator and property registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["operator","Operator","text","Red Basin Operating"],["wellAfe","Well / AFE","text","WELL-42 / AFE-1088"],["billedAmount","Operator Billed Amount","currency",1380000],["supportedAmount","Supported Net Share","currency",1195000]],{amountField:"billedAmount",subjects:["Operated producing well","Non-operated drilling AFE","Completion project","Workover program","Saltwater disposal facility"]}),
feature("joa-and-copas-term-library","JAR02","JOA and COPAS term library","Reconcile joa and copas term library using JOAs, COPAS accounting procedures, division-of-interest records, AFEs, field tickets, material transfers, and JIB statements.","Produce a governed joa and copas term library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["operator","Operator","text","Red Basin Operating"],["wellAfe","Well / AFE","text","WELL-42 / AFE-1088"],["billedAmount","Operator Billed Amount","currency",1380000],["supportedAmount","Supported Net Share","currency",1195000]],{amountField:"billedAmount",subjects:["Operated producing well","Non-operated drilling AFE","Completion project","Workover program","Saltwater disposal facility"]}),
feature("division-of-interest-validation","JAR03","Division-of-interest validation","Reconcile division-of-interest validation using JOAs, COPAS accounting procedures, division-of-interest records, AFEs, field tickets, material transfers, and JIB statements.","Produce a governed division-of-interest validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["operator","Operator","text","Red Basin Operating"],["wellAfe","Well / AFE","text","WELL-42 / AFE-1088"],["billedAmount","Operator Billed Amount","currency",1380000],["supportedAmount","Supported Net Share","currency",1195000]],{amountField:"billedAmount",subjects:["Operated producing well","Non-operated drilling AFE","Completion project","Workover program","Saltwater disposal facility"]}),
feature("jib-statement-ingestion","JAR04","JIB statement ingestion","Reconcile jib statement ingestion using JOAs, COPAS accounting procedures, division-of-interest records, AFEs, field tickets, material transfers, and JIB statements.","Produce a governed jib statement ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["operator","Operator","text","Red Basin Operating"],["wellAfe","Well / AFE","text","WELL-42 / AFE-1088"],["billedAmount","Operator Billed Amount","currency",1380000],["supportedAmount","Supported Net Share","currency",1195000]],{amountField:"billedAmount",subjects:["Operated producing well","Non-operated drilling AFE","Completion project","Workover program","Saltwater disposal facility"]}),
feature("afe-authority-and-budget-control","JAR05","AFE authority and budget control","Reconcile afe authority and budget control using JOAs, COPAS accounting procedures, division-of-interest records, AFEs, field tickets, material transfers, and JIB statements.","Produce a governed afe authority and budget control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["operator","Operator","text","Red Basin Operating"],["wellAfe","Well / AFE","text","WELL-42 / AFE-1088"],["billedAmount","Operator Billed Amount","currency",1380000],["supportedAmount","Supported Net Share","currency",1195000]],{amountField:"billedAmount",subjects:["Operated producing well","Non-operated drilling AFE","Completion project","Workover program","Saltwater disposal facility"]}),
feature("working-interest-recalculation","JAR06","Working-interest recalculation","Reconcile working-interest recalculation using JOAs, COPAS accounting procedures, division-of-interest records, AFEs, field tickets, material transfers, and JIB statements.","Produce a governed working-interest recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["operator","Operator","text","Red Basin Operating"],["wellAfe","Well / AFE","text","WELL-42 / AFE-1088"],["billedAmount","Operator Billed Amount","currency",1380000],["supportedAmount","Supported Net Share","currency",1195000]],{amountField:"billedAmount",subjects:["Operated producing well","Non-operated drilling AFE","Completion project","Workover program","Saltwater disposal facility"]}),
feature("overhead-rate-validation","JAR07","Overhead-rate validation","Reconcile overhead-rate validation using JOAs, COPAS accounting procedures, division-of-interest records, AFEs, field tickets, material transfers, and JIB statements.","Produce a governed overhead-rate validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["operator","Operator","text","Red Basin Operating"],["wellAfe","Well / AFE","text","WELL-42 / AFE-1088"],["billedAmount","Operator Billed Amount","currency",1380000],["supportedAmount","Supported Net Share","currency",1195000]],{amountField:"billedAmount",subjects:["Operated producing well","Non-operated drilling AFE","Completion project","Workover program","Saltwater disposal facility"]}),
feature("direct-charge-allowability","JAR08","Direct-charge allowability","Reconcile direct-charge allowability using JOAs, COPAS accounting procedures, division-of-interest records, AFEs, field tickets, material transfers, and JIB statements.","Produce a governed direct-charge allowability decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["operator","Operator","text","Red Basin Operating"],["wellAfe","Well / AFE","text","WELL-42 / AFE-1088"],["billedAmount","Operator Billed Amount","currency",1380000],["supportedAmount","Supported Net Share","currency",1195000]],{amountField:"billedAmount",subjects:["Operated producing well","Non-operated drilling AFE","Completion project","Workover program","Saltwater disposal facility"]}),
feature("material-transfer-pricing-audit","JAR09","Material transfer pricing audit","Reconcile material transfer pricing audit using JOAs, COPAS accounting procedures, division-of-interest records, AFEs, field tickets, material transfers, and JIB statements.","Produce a governed material transfer pricing audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["operator","Operator","text","Red Basin Operating"],["wellAfe","Well / AFE","text","WELL-42 / AFE-1088"],["billedAmount","Operator Billed Amount","currency",1380000],["supportedAmount","Supported Net Share","currency",1195000]],{amountField:"billedAmount",subjects:["Operated producing well","Non-operated drilling AFE","Completion project","Workover program","Saltwater disposal facility"]}),
feature("affiliate-and-related-party-review","JAR10","Affiliate and related-party review","Reconcile affiliate and related-party review using JOAs, COPAS accounting procedures, division-of-interest records, AFEs, field tickets, material transfers, and JIB statements.","Produce a governed affiliate and related-party review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["operator","Operator","text","Red Basin Operating"],["wellAfe","Well / AFE","text","WELL-42 / AFE-1088"],["billedAmount","Operator Billed Amount","currency",1380000],["supportedAmount","Supported Net Share","currency",1195000]],{amountField:"billedAmount",subjects:["Operated producing well","Non-operated drilling AFE","Completion project","Workover program","Saltwater disposal facility"]}),
feature("field-ticket-evidence-matching","JAR11","Field-ticket evidence matching","Reconcile field-ticket evidence matching using JOAs, COPAS accounting procedures, division-of-interest records, AFEs, field tickets, material transfers, and JIB statements.","Produce a governed field-ticket evidence matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["operator","Operator","text","Red Basin Operating"],["wellAfe","Well / AFE","text","WELL-42 / AFE-1088"],["billedAmount","Operator Billed Amount","currency",1380000],["supportedAmount","Supported Net Share","currency",1195000]],{amountField:"billedAmount",subjects:["Operated producing well","Non-operated drilling AFE","Completion project","Workover program","Saltwater disposal facility"]}),
feature("duplicate-and-prior-period-detection","JAR12","Duplicate and prior-period detection","Reconcile duplicate and prior-period detection using JOAs, COPAS accounting procedures, division-of-interest records, AFEs, field tickets, material transfers, and JIB statements.","Produce a governed duplicate and prior-period detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["operator","Operator","text","Red Basin Operating"],["wellAfe","Well / AFE","text","WELL-42 / AFE-1088"],["billedAmount","Operator Billed Amount","currency",1380000],["supportedAmount","Supported Net Share","currency",1195000]],{amountField:"billedAmount",subjects:["Operated producing well","Non-operated drilling AFE","Completion project","Workover program","Saltwater disposal facility"]}),
feature("operator-exception-package","JAR13","Operator exception package","Reconcile operator exception package using JOAs, COPAS accounting procedures, division-of-interest records, AFEs, field tickets, material transfers, and JIB statements.","Produce a governed operator exception package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["operator","Operator","text","Red Basin Operating"],["wellAfe","Well / AFE","text","WELL-42 / AFE-1088"],["billedAmount","Operator Billed Amount","currency",1380000],["supportedAmount","Supported Net Share","currency",1195000]],{amountField:"billedAmount",subjects:["Operated producing well","Non-operated drilling AFE","Completion project","Workover program","Saltwater disposal facility"]}),
feature("audit-deadline-and-response-tracking","JAR14","Audit deadline and response tracking","Reconcile audit deadline and response tracking using JOAs, COPAS accounting procedures, division-of-interest records, AFEs, field tickets, material transfers, and JIB statements.","Produce a governed audit deadline and response tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["operator","Operator","text","Red Basin Operating"],["wellAfe","Well / AFE","text","WELL-42 / AFE-1088"],["billedAmount","Operator Billed Amount","currency",1380000],["supportedAmount","Supported Net Share","currency",1195000]],{amountField:"billedAmount",subjects:["Operated producing well","Non-operated drilling AFE","Completion project","Workover program","Saltwater disposal facility"]}),
feature("recovery-and-operator-analytics","JAR15","Recovery and operator analytics","Reconcile recovery and operator analytics using JOAs, COPAS accounting procedures, division-of-interest records, AFEs, field tickets, material transfers, and JIB statements.","Produce a governed recovery and operator analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["operator","Operator","text","Red Basin Operating"],["wellAfe","Well / AFE","text","WELL-42 / AFE-1088"],["billedAmount","Operator Billed Amount","currency",1380000],["supportedAmount","Supported Net Share","currency",1195000]],{amountField:"billedAmount",subjects:["Operated producing well","Non-operated drilling AFE","Completion project","Workover program","Saltwater disposal facility"]})
]);
